shell:
  program: /usr/bin/zsh
  args:
    - --login

# カーソル
cursor:
  text: '#ffffff'
  cursor: '#00ff00'
  style:
    shape: Underline
    blinking: On
  unfocused_hollow: false
  blink_interval: 470



# タブスペース
tabspaces: 4

# フォント
font:
  size: 13.5
  normal:
    family: 'Ricty'
    style: Regular
  bold:
    family: 'Ricty'
    style: Bold
  italic:
    family: 'Ricty'
    style: Italic
  bold_italic:
    family: 'Ricty'
    style: Bold Italic

# ウインドウ
window:
  decorations: full
  dimensions:
          columms: 120
          line: 100

# 透過
background_opacity: 0.99

# 環境変数
env:
  TERM: alacritty

# テーマ
# KDE Breeze (Ported from Konsole)
colors:
  # Default colors
  primary:
    background: '#232627'
    foreground: '#fcfcfc'

    dim_foreground: '#eff0f1'
    bright_foreground: '#ffffff'
    dim_background: '#31363b'
    bright_background: '#000000'

  # Normal colors
  normal:
    black: '#232627'
    red: '#ed1515'
    green: '#11d116'
    yellow: '#f67400'
    blue: '#1d99f3'
    magenta: '#9b59b6'
    cyan: '#1abc9c'
    white: '#fcfcfc'

  # Bright colors
  bright:
    black: '#7f8c8d'
    red: '#c0392b'
    green: '#1cdc9a'
    yellow: '#fdbc4b'
    blue: '#3daee9'
    magenta: '#8e44ad'
    cyan: '#16a085'
    white: '#ffffff'

  # Dim colors
  dim:
    black: '#31363b'
    red: '#783228'
    green: '#17a262'
    yellow: '#b65619'
    blue: '#1b668f'
    magenta: '#614a73'
    cyan: '#186c60'
    white: '#63686d'