# prefixキーをC-aに変更する
set -g prefix C-a

# C-bのキーバインドを解除する
unbind C-b

# デフォルトシェルの設定
set-option -g default-shell /bin/zsh
set-option -g default-command /bin/zsh

# キーストロークのディレイを減らす
set -sg escape-time 0

# ウィンドウのインデックスを1から始める
set -g base-index 1

# ペインのインデックスを1から始める
setw -g pane-base-index 1

# ボーダーの太さ
set -g pane-border-lines heavy

# 設定ファイルをリロードする
bind r source-file ~/.tmux.conf \; display "Reloaded."

# C-a*2でtmux内のプログラムにC-aを送る
bind C-a send-prefix

# ウインドウ操作
bind-key -n M-s split-window -h -c "#{pane_current_path}"
bind-key -n M-v split-window -v -c "#{pane_current_path}"

bind-key s split-window -v
bind-key v split-window -h

bind-key -n M-Left select-pane -L
bind-key -n M-Right select-pane -R
bind-key -n M-Up select-pane -U
bind-key -n M-Down select-pane -D

bind-key -n M-h select-pane -L
bind-key -n M-l select-pane -R
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U

bind-key -n M-w kill-pane

# Vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# 256色端末を使用する
set -g default-terminal "screen-256color"

# ステータスバーの色を設定する
set-option -g status-style fg=white,bg=default

# ウィンドウリストの色を設定する
set-window-option -g window-status-style fg=white
set-window-option -g window-status-style bg=default
set-window-option -g window-status-style dim
# アクティブなウィンドウを目立たせる
setw -g window-status-current-style fg=red,bg=default
setw -g window-status-current-style bright

# ペインボーダーの色を設定する
set -g pane-border-style fg=green,bg=black

# コマンドラインの色を設定する
set -g message-style fg=white,bg=black
set -g message-style bright

# ステータスバーを設定する
## 左パネルを設定する
set -g status-left-length 40
set -g status-left "#[fg=green]#S #[fg=yellow]#I #[fg=cyan]#P "
## 右パネルを設定する
set -g status-right ""
## リフレッシュの間隔を設定する(デフォルト 15秒)
set -g status-interval 1
## ヴィジュアルノーティフィケーションを有効にする
setw -g monitor-activity on
set -g visual-activity on

## Alcrittyでtmuxを有効にする
set-option -sa terminal-overrides ',alacritty:RGB'
