[[plugins]]
 repo = 'Shougo/deoplete.nvim'
 hook_add = '''
   let g:deoplete#enable_at_startup = 1
   let g:deoplete#enable_ignore_case = 1
'''
# deoplete on vim requires plugin 1/2
[[plugins]]
 repo = 'roxma/nvim-yarp'

# deoplete on vim requires plugin 2/2
[[plugins]]
 repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
 repo = 'Shougo/neco-vim'

[[plugins]]
 repo = 'Shougo/neco-syntax'

[[plugins]]
 repo = 'itchyny/lightline.vim'

[[plugins]]
 repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
 repo = 'cohama/lexima.vim'

[[plugins]]
 repo = 'preservim/nerdtree'

[[plugins]]
 repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
 repo = 'ryanoasis/vim-devicons'

[[plugins]]
 repo = 'junegunn/fzf'
 build_on = '''
 ./install -all
'''

[[plugins]]
 repo = 'junegunn/fzf.vim'

[[plugins]]
 repo = 'lambdalisue/suda.vim'

[[pliugins]]
 repo = 'tpope/vim-fugitive'

[[plugins]]
 repo = 'tomasr/molokai'
