[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
 let g:deoplete#enable_at_startup = 1
 inoremap <silent><expr> <TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
'''

#deoplete on vim requires plugin 1/2
[[plugins]]
 repo = 'roxma/nvim-yarp'

# deoplete on vim requires plugin 2/2
[[plugins]]
 repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
 repo = 'Shougo/neco-vim'

[[plugins]]
 repo = 'vim-airline/vim-airline'

[[plugins]]
 repo = 'vim-airline/vim-airline-themes'

[[plugins]]
 repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
 repo = 'cohama/lexima.vim'

[[plugins]]
 repo = 'lambdalisue/fern.vim'
 hook_add = '''
 nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>
 let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
 repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
 repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
 repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
 repo = 'ryanoasis/vim-devicons'

[[plugins]]
 repo = 'junegunn/fzf'
 build_on = '''
 ./install -all
'''

[[plugins]]
 repo = 'junegunn/fzf.vim'

[[plugins]]
 repo = 'lambdalisue/suda.vim'

[[plugins]]
 repo = 'tpope/vim-fugitive'

[[plugins]]
 repo = 'airblade/vim-gitgutter'
 hook_add = '''
    set signcolumn=yes
    let g:gitgutter_async = 1
    let g:gitgutter_sign_modified = 'rw'
    highlight GitGutterAdd ctermfg=green
    highlight GitGutterChange ctermfg=yellow
    highlight GitGutterDelete ctermfg=red
    highlight GitGutterChangeDelete ctermfg=yellow
'''

[[plugins]]
 repo = 'ntk148v/vim-horizon'

[[plugins]]
 repo = 'sheerun/vim-polyglot'

[[plugins]]
 repo = 'gko/vim-coloresque'

[[plugins]]
 repo = 'tomtom/tcomment_vim'
 hook_add = '''
    vnoremap ? :'<,'>TComment<CR>
'''

[[plugins]]
 repo = 'tpope/vim-commentary'

[[plugins]]
 repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
 repo = 'simeji/winresizer'
