# シェル
shell:
  program: /usr/bin/zsh
  args:
    - --login

# カーソル
cursor:
  style:
    shape: Underline
    blinking: Always
  unfocused_hollow: false
  blink_interval: 470

# タブスペース
tabspaces: 4

# ウインドウ
window:
  opacity: 0.95
  padding:
   x: 0
   y: 0
  dynamic_padding: false

# フォント
font:
  size: 20
  normal:
    family: 'UDEV Gothic 35NFLG'
    style: Regular
  bold:
    family: 'UDEV Gothic 35NFLG'
    style: Bold
  italic:
    family: 'UDEV Gothic 35NFLG'
    style: Italic
  bold_italic:
    family: 'UDEV Gothic 35NFLG'
    style: Bold Italic

# 環境変数
env:
  WINIT_X11_SCALE_FACTOR: '1.0'
  TERM: xterm-256color

# Colors (Horizon Dark)
colors:
  # Primary colors
  primary:
    background: '0x1c1e26'
    foreground: '0xe0e0e0'

  # Cursor
  cursor:
    cursor: '0x00ff00'
  vi_mode_cursor:
    cursor: '0x00ff00'

  # Normal colors
  normal:
    black: '0x16161c'
    red: '0xe95678'
    green: '0x29d398'
    yellow: '0xfab795'
    blue: '0x26bbd9'
    magenta: '0xee64ac'
    cyan: '0x59e1e3'
    white: '0xd5d8da'

  # Bright colors
  bright:
    black: '0x5b5858'
    red: '0xec6a88'
    green: '0x3fdaa4'
    yellow: '0xfbc3a7'
    blue: '0x3fc4de'
    magenta: '0xf075b5'
    cyan: '0x6be4e6'
    white: '0xd5d8da'
